"""add wamp_session table

Revision ID: 1c0575e1ba09
Revises: 2c7e72c420e9
Create Date: 2015-01-05 22:43:54.396995

"""

# revision identifiers, used by Alembic.
revision = '1c0575e1ba09'
down_revision = '2c7e72c420e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wamp_session',
    sa.Column('sessionid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sessionid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wamp_session')
    ### end Alembic commands ###
