"""add description to object

Revision ID: 1c42fab426e8
Revises: 26a99a9ae26b
Create Date: 2015-12-02 21:37:07.093805

"""

# revision identifiers, used by Alembic.
revision = '1c42fab426e8'
down_revision = '26a99a9ae26b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'description')
    ### end Alembic commands ###
