"""add groupLocShare table

Revision ID: 26c2e3b63643
Revises: 572a637f3d4c
Create Date: 2015-12-05 17:13:00.663040

"""

# revision identifiers, used by Alembic.
revision = '26c2e3b63643'
down_revision = '572a637f3d4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_loc_share',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('groupid', 'userid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_loc_share')
    ### end Alembic commands ###
