"""empty message

Revision ID: 2709792fc2f9
Revises: None
Create Date: 2014-09-22 23:13:14.752348

"""

# revision identifiers, used by Alembic.
revision = '2709792fc2f9'
down_revision = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_key',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('user', sa.String(length=80), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('track_person',
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('device', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('hdg', sa.Float(), nullable=True),
    sa.Column('spd', sa.Float(), nullable=True),
    sa.Column('extra', sa.String(length=512), nullable=True),
    sa.Column('lastupd', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('device')
    )
    op.create_table('follower',
    sa.Column('follower', sa.String(length=80), nullable=False),
    sa.Column('following', sa.String(length=80), nullable=False),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['users.username'], ),
    sa.ForeignKeyConstraint(['following'], ['users.username'], ),
    sa.PrimaryKeyConstraint('follower', 'following')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


# no downgrade as you probably don't want to do that
