"""create AuthTicket

Revision ID: 2c7e72c420e9
Revises: 529e38736245
Create Date: 2014-12-15 23:40:43.729706

"""

# revision identifiers, used by Alembic.
revision = '2c7e72c420e9'
down_revision = '529e38736245'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_ticket',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_ticket')
    ### end Alembic commands ###
