"""add geocode cache

Revision ID: 3d00d4c92b47
Revises: 3fa7cb351535
Create Date: 2017-02-05 10:24:43.069555

"""

# revision identifiers, used by Alembic.
revision = '3d00d4c92b47'
down_revision = '3fa7cb351535'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('geohash', sa.String(length=8), nullable=False),
    sa.Column('geocode', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('geohash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
