"""add primary key to follower

Revision ID: 51c799adcfb1
Revises: 1c0575e1ba09
Create Date: 2015-01-07 15:45:21.627404

"""

# revision identifiers, used by Alembic.
revision = '51c799adcfb1'
down_revision = '1c0575e1ba09'

from alembic import op
import sqlalchemy as sa


def upgrade():
	with op.batch_alter_table('follower', schema=None) as batch_op:
		batch_op.rename_table('follower', 'follower2')
	
	op.create_table('follower',
	sa.Column('follower', sa.Integer(), nullable=False),
	sa.Column('following', sa.Integer(), nullable=False),
	sa.Column('confirmed', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
	sa.ForeignKeyConstraint(['following'], ['users.id'], ),
	sa.PrimaryKeyConstraint('follower', 'following')
	)
	
	conn = op.get_bind()
	conn.execute("insert into follower (select follower, following, confirmed from follower2)")
	
	op.drop_table('follower2')
	### commands auto generated by Alembic - please adjust! ###
	#pass
	### end Alembic commands ###


#def downgrade():
#    ### commands auto generated by Alembic - please adjust! ###
#    pass
#    ### end Alembic commands ###
#	op.drop_table('follower')
#	with op.batch_alter_table('follower', schema=None) as batch_op:
#		batch_op.rename_table('follower2', 'follower')
